# theme       : jekyll-theme-slate
title       : "Kernel Themes"
description : "A repository for flashcart kernel themes"
repo        : "flashcarts/kernel-themes"
color       : "#B23456"
image       : "/assets/images/favicon/favicon-196x196.png"

sass:
  sass_dir: _sass

exclude:
  - Gemfile*
  - vendor
  - LICENSE*

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  akmenu:
    output: true
    title: "WoodR4/AKMenu"
    image: "/assets/images/site-images/AKMenu_TitlePage.png"
  ysmenu:
    output: true
    title: "YSMenu"
    image: "/assets/images/site-images/YSMenu_TitlePage.png"
  moonshell2:
    output: true
    title: "Moonshell 2"
    image: "/assets/images/site-images/MS2_TitlePage.png"